
CREATE TABLE GEO_CLIENTE (
	ID_CLIENTE BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    NOME_RAZAO_SOCIAL VARCHAR(100) NOT NULL,
	SOBRENOME VARCHAR(100) NOT NULL,
	IND_PESSOA_FISICA INT(1)  NOT NULL,
	CPF INT(11),
    CNPJ INT(14),
    EMAIL VARCHAR(50) NOT NULL,
	TELEFONE VARCHAR(50) NOT NULL,
    CELULAR VARCHAR(50),
    FLAG_STATUS VARCHAR(1),
    DT_INCLUSAO DATETIME NOT NULL,
	DT_ALTERACAO DATETIME NOT NULL,
	VERSAO_SISTEMA BIGINT(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE GEO_USUARIO (
	ID_USUARIO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	SOBRENOME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	TELEFONE VARCHAR(50) NOT NULL,
	SENHA VARCHAR(150) NOT NULL,
	FLAG_PERFIL VARCHAR(5) NOT NULL,
    ID_CLIENTE BIGINT(20) NOT NULL,
	IND_ATIVO INT(1) NOT NULL,
	DT_INCLUSAO DATETIME NOT NULL,
	DT_ALTERACAO DATETIME NOT NULL,
	VERSAO_SISTEMA BIGINT(5) NOT NULL,
	FOREIGN KEY (ID_CLIENTE) REFERENCES GEO_CLIENTE(ID_CLIENTE)

) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE GEO_CONFIGURACAO (
	ID_CONFIGURACAO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	URL VARCHAR(100) NOT NULL,
	ID_DISPOSITIVO BIGINT(20) NOT NULL,
	DT_SINCRONIZACAO DATETIME NOT NULL,
	DT_INCLUSAO DATETIME NOT NULL,
	DT_ALTERACAO DATETIME NOT NULL,
	VERSAO_SISTEMA BIGINT(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE GEO_DISPOSITIVO (
	ID_DISPOSITIVO BIGINT(20) PRIMARY KEY,
	DT_SINCRONIZACAO DATETIME NOT NULL,
	DT_INCLUSAO DATETIME NOT NULL,
	DT_ALTERACAO DATETIME NOT NULL,
	VERSAO_SISTEMA BIGINT(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE GEO_TIPO_CULTIVO (
	ID_TIPO_CULTIVO BIGINT(20) PRIMARY KEY,
	DESCRICAO VARCHAR(50) NOT NULL,
	IND_ATIVO INT(1) NOT NULL,
	DT_INCLUSAO DATETIME NOT NULL,
	DT_ALTERACAO DATETIME NOT NULL,
	VERSAO_SISTEMA BIGINT(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE GEO_DOENCA (
	ID_DOENCA BIGINT(20) PRIMARY KEY,
	DESCRICAO VARCHAR(100) NOT NULL,
    DESCRICAO_CIENTIFICA VARCHAR(100) NOT NULL,
    ID_TIPO_CULTIVO BIGINT(20),
	IND_ATIVO INT(1) NOT NULL,
	DT_INCLUSAO DATETIME NOT NULL,
	DT_ALTERACAO DATETIME NOT NULL,
	VERSAO_SISTEMA BIGINT(5) NOT NULL,
    FOREIGN KEY (ID_TIPO_CULTIVO) REFERENCES GEO_TIPO_CULTIVO(ID_TIPO_CULTIVO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE GEO_PRAGA (
	ID_PRAGA BIGINT(20) PRIMARY KEY,
	DESCRICAO VARCHAR(100) NOT NULL,
    DESCRICAO_CIENTIFICA VARCHAR(100) NOT NULL,
    ID_TIPO_CULTIVO BIGINT(20),
	IND_ATIVO INT(1) NOT NULL,
	DT_INCLUSAO DATETIME NOT NULL,
	DT_ALTERACAO DATETIME NOT NULL,
	VERSAO_SISTEMA BIGINT(5) NOT NULL,
    FOREIGN KEY (ID_TIPO_CULTIVO) REFERENCES GEO_TIPO_CULTIVO(ID_TIPO_CULTIVO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE GEO_ROTA_TRABALHO (
	ID_ROTA_TRABALHO_DISP BIGINT(20) PRIMARY KEY,
	LATITUDE NUMERIC(20,10) NOT NULL,
    LONGITUDE NUMERIC(20,10) NOT NULL,
    ID_CLIENTE BIGINT(20) NOT NULL,
	ID_DISPOSITIVO BIGINT(20) NOT NULL,
	ID_ROTA_TRABALHO BIGINT(20),
    ID_USUARIO_REG BIGINT(20) NOT NULL,
	DT_INCLUSAO DATETIME NOT NULL,
	DT_ALTERACAO DATETIME NOT NULL,
	VERSAO_SISTEMA BIGINT(5) NOT NULL,
    FOREIGN KEY (ID_USUARIO_REG) REFERENCES GEO_USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_CLIENTE)     REFERENCES GEO_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_DISPOSITIVO) REFERENCES GEO_DISPOSITIVO(ID_DISPOSITIVO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE GEO_PONTO_COLETA_CHUVA (
	ID_PONTO_COLETA_CHUVA_DISP BIGINT(20) PRIMARY KEY,
	DESCRICAO VARCHAR(100) NOT NULL,
    LATITUDE NUMERIC(20,10) NOT NULL,
    LONGITUDE NUMERIC(20,10) NOT NULL,
    DT_INSTALACAO DATETIME NOT NULL,
    IND_ATIVO INT(1) NOT NULL,
	ID_CLIENTE BIGINT(20) NOT NULL,
	ID_DISPOSITIVO BIGINT(20) NOT NULL,
	ID_PONTO_COLETA_CHUVA BIGINT(20),
	ID_USUARIO_REG BIGINT(20) NOT NULL,
	DT_INCLUSAO DATETIME NOT NULL,
	DT_ALTERACAO DATETIME NOT NULL,
	VERSAO_SISTEMA BIGINT(5) NOT NULL,
    FOREIGN KEY (ID_USUARIO_REG) REFERENCES GEO_USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_CLIENTE)     REFERENCES GEO_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_DISPOSITIVO) REFERENCES GEO_DISPOSITIVO(ID_DISPOSITIVO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE GEO_REGISTRO_CHUVA (
	ID_REGISTRO_CHUVA_DISP BIGINT(20) PRIMARY KEY,
	VOLUME INT(10) NOT NULL,
    OBSERVACAO VARCHAR(100) ,
    LATITUDE NUMERIC(20,10) NOT NULL,
    LONGITUDE NUMERIC(20,10) NOT NULL,
    ID_PONTO_COLETA_CHUVA_DISP BIGINT(20) NOT NULL,
    ID_CLIENTE BIGINT(20) NOT NULL,
	ID_DISPOSITIVO BIGINT(20) NOT NULL,
	ID_REGISTRO_CHUVA BIGINT(20),
	ID_USUARIO_REG BIGINT(20) NOT NULL,
	DT_INCLUSAO DATETIME NOT NULL,
	DT_ALTERACAO DATETIME NOT NULL,
	VERSAO_SISTEMA BIGINT(5) NOT NULL,
    FOREIGN KEY (ID_PONTO_COLETA_CHUVA_DISP) REFERENCES GEO_PONTO_COLETA_CHUVA(ID_PONTO_COLETA_CHUVA_DISP),
    FOREIGN KEY (ID_USUARIO_REG) REFERENCES GEO_USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_CLIENTE)     REFERENCES GEO_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_DISPOSITIVO) REFERENCES GEO_DISPOSITIVO(ID_DISPOSITIVO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE GEO_REGISTRO_PRAGA (
	ID_REGISTRO_PRAGA_DISP BIGINT(20) PRIMARY KEY,
	QTDE INT(10) NOT NULL,
    OBSERVACAO VARCHAR(100) ,
    LATITUDE NUMERIC(20,10) NOT NULL,
    LONGITUDE NUMERIC(20,10) NOT NULL,
    ID_PRAGA BIGINT(20) NOT NULL,
    ID_CLIENTE BIGINT(20) NOT NULL,
	ID_DISPOSITIVO BIGINT(20) NOT NULL,
	ID_REGISTRO_PRAGA BIGINT(20),
	ID_USUARIO_REG BIGINT(20) NOT NULL,
	DT_INCLUSAO DATETIME NOT NULL,
	DT_ALTERACAO DATETIME NOT NULL,
	VERSAO_SISTEMA BIGINT(5) NOT NULL,
    FOREIGN KEY (ID_PRAGA) REFERENCES GEO_PRAGA(ID_PRAGA),
    FOREIGN KEY (ID_USUARIO_REG) REFERENCES GEO_USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_CLIENTE)     REFERENCES GEO_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_DISPOSITIVO) REFERENCES GEO_DISPOSITIVO(ID_DISPOSITIVO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE GEO_REGISTRO_DOENCA (
	ID_REGISTRO_DOENCA_DISP BIGINT(20) PRIMARY KEY,
	OBSERVACAO VARCHAR(100) ,
    LATITUDE NUMERIC(20,10) NOT NULL,
    LONGITUDE NUMERIC(20,10) NOT NULL,
    ID_DOENCA BIGINT(20) NOT NULL,
    ID_CLIENTE BIGINT(20) NOT NULL,
	ID_DISPOSITIVO BIGINT(20) NOT NULL,
	ID_REGISTRO_DOENCA BIGINT(20),
	ID_USUARIO_REG BIGINT(20) NOT NULL,
	DT_INCLUSAO DATETIME NOT NULL,
	DT_ALTERACAO DATETIME NOT NULL,
	VERSAO_SISTEMA BIGINT(5) NOT NULL,
    FOREIGN KEY (ID_DOENCA) REFERENCES GEO_DOENCA(ID_DOENCA),
    FOREIGN KEY (ID_USUARIO_REG) REFERENCES GEO_USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_CLIENTE)     REFERENCES GEO_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_DISPOSITIVO) REFERENCES GEO_DISPOSITIVO(ID_DISPOSITIVO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE GEO_REGISTRO_IMAGEM (
	ID_REGISTRO_IMAGEM_DISP BIGINT(20) PRIMARY KEY,
	OBSERVACAO VARCHAR(100) ,
    LATITUDE NUMERIC(20,10) NOT NULL,
    LONGITUDE NUMERIC(20,10) NOT NULL,
    IMAGEM BLOB NOT NULL,
    ID_CLIENTE BIGINT(20) NOT NULL,
	ID_DISPOSITIVO BIGINT(20) NOT NULL,
	ID_REGISTRO_IMAGEM BIGINT(20),
	ID_USUARIO_REG BIGINT(20) NOT NULL,
	DT_INCLUSAO DATETIME NOT NULL,
	DT_ALTERACAO DATETIME NOT NULL,
	VERSAO_SISTEMA BIGINT(5) NOT NULL,
    FOREIGN KEY (ID_USUARIO_REG) REFERENCES GEO_USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_CLIENTE)     REFERENCES GEO_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_DISPOSITIVO) REFERENCES GEO_DISPOSITIVO(ID_DISPOSITIVO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
