package br.com.geodrone.model.daoGen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import br.com.geodrone.model.ClienteUsuario;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GEO_CLIENTE_USUARIO".
*/
public class ClienteUsuarioDao extends AbstractDao<ClienteUsuario, Long> {

    public static final String TABLENAME = "GEO_CLIENTE_USUARIO";

    /**
     * Properties of entity ClienteUsuario.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID_CLIENTE_USUARIO");
        public final static Property IdUsuario = new Property(1, Long.class, "idUsuario", false, "ID_USUARIO");
        public final static Property IndPadrao = new Property(2, Integer.class, "indPadrao", false, "IND_PADRAO");
        public final static Property IdCliente = new Property(3, Long.class, "idCliente", false, "ID_CLIENTE");
        public final static Property IndAtivo = new Property(4, Integer.class, "indAtivo", false, "IND_ATIVO");
        public final static Property DtInclusao = new Property(5, java.util.Date.class, "dtInclusao", false, "DT_INCLUSAO");
        public final static Property DtAlteracao = new Property(6, java.util.Date.class, "dtAlteracao", false, "DT_ALTERACAO");
        public final static Property VersaoSistema = new Property(7, Long.class, "versaoSistema", false, "VERSAO_SISTEMA");
    }


    public ClienteUsuarioDao(DaoConfig config) {
        super(config);
    }
    
    public ClienteUsuarioDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GEO_CLIENTE_USUARIO\" (" + //
                "\"ID_CLIENTE_USUARIO\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ID_USUARIO\" INTEGER NOT NULL ," + // 1: idUsuario
                "\"IND_PADRAO\" INTEGER NOT NULL ," + // 2: indPadrao
                "\"ID_CLIENTE\" INTEGER NOT NULL ," + // 3: idCliente
                "\"IND_ATIVO\" INTEGER NOT NULL ," + // 4: indAtivo
                "\"DT_INCLUSAO\" INTEGER NOT NULL ," + // 5: dtInclusao
                "\"DT_ALTERACAO\" INTEGER NOT NULL ," + // 6: dtAlteracao
                "\"VERSAO_SISTEMA\" INTEGER NOT NULL );"); // 7: versaoSistema
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GEO_CLIENTE_USUARIO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ClienteUsuario entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIdUsuario());
        stmt.bindLong(3, entity.getIndPadrao());
        stmt.bindLong(4, entity.getIdCliente());
        stmt.bindLong(5, entity.getIndAtivo());
        stmt.bindLong(6, entity.getDtInclusao().getTime());
        stmt.bindLong(7, entity.getDtAlteracao().getTime());
        stmt.bindLong(8, entity.getVersaoSistema());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ClienteUsuario entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIdUsuario());
        stmt.bindLong(3, entity.getIndPadrao());
        stmt.bindLong(4, entity.getIdCliente());
        stmt.bindLong(5, entity.getIndAtivo());
        stmt.bindLong(6, entity.getDtInclusao().getTime());
        stmt.bindLong(7, entity.getDtAlteracao().getTime());
        stmt.bindLong(8, entity.getVersaoSistema());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ClienteUsuario readEntity(Cursor cursor, int offset) {
        ClienteUsuario entity = new ClienteUsuario();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ClienteUsuario entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdUsuario(cursor.getLong(offset + 1));
        entity.setIndPadrao(cursor.getInt(offset + 2));
        entity.setIdCliente(cursor.getLong(offset + 3));
        entity.setIndAtivo(cursor.getInt(offset + 4));
        entity.setDtInclusao(new java.util.Date(cursor.getLong(offset + 5)));
        entity.setDtAlteracao(new java.util.Date(cursor.getLong(offset + 6)));
        entity.setVersaoSistema(cursor.getLong(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ClienteUsuario entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ClienteUsuario entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ClienteUsuario entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
