package br.com.geodrone.model.daoGen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import br.com.geodrone.model.Configuracao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TB_CONFIGURACAO".
*/
public class ConfiguracaoDao extends AbstractDao<Configuracao, Long> {

    public static final String TABLENAME = "TB_CONFIGURACAO";

    /**
     * Properties of entity Configuracao.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID_ROTA_TRABALHO");
        public final static Property IdDispositivo = new Property(1, Long.class, "idDispositivo", false, "ID_DISPOSITIVO");
        public final static Property Url = new Property(2, String.class, "url", false, "URL");
        public final static Property DtSincronizacao = new Property(3, java.util.Date.class, "dtSincronizacao", false, "DT_SINCRONIZACAO");
    }


    public ConfiguracaoDao(DaoConfig config) {
        super(config);
    }
    
    public ConfiguracaoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TB_CONFIGURACAO\" (" + //
                "\"ID_ROTA_TRABALHO\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ID_DISPOSITIVO\" INTEGER NOT NULL ," + // 1: idDispositivo
                "\"URL\" TEXT NOT NULL ," + // 2: url
                "\"DT_SINCRONIZACAO\" INTEGER);"); // 3: dtSincronizacao
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TB_CONFIGURACAO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Configuracao entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIdDispositivo());
        stmt.bindString(3, entity.getUrl());
 
        java.util.Date dtSincronizacao = entity.getDtSincronizacao();
        if (dtSincronizacao != null) {
            stmt.bindLong(4, dtSincronizacao.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Configuracao entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getIdDispositivo());
        stmt.bindString(3, entity.getUrl());
 
        java.util.Date dtSincronizacao = entity.getDtSincronizacao();
        if (dtSincronizacao != null) {
            stmt.bindLong(4, dtSincronizacao.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Configuracao readEntity(Cursor cursor, int offset) {
        Configuracao entity = new Configuracao();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Configuracao entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdDispositivo(cursor.getLong(offset + 1));
        entity.setUrl(cursor.getString(offset + 2));
        entity.setDtSincronizacao(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Configuracao entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Configuracao entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Configuracao entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
