package br.com.geodrone.model.daoGen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import br.com.geodrone.model.Cliente;
import br.com.geodrone.model.Configuracao;
import br.com.geodrone.model.Doenca;
import br.com.geodrone.model.PerfilUsuario;
import br.com.geodrone.model.PontoColetaChuva;
import br.com.geodrone.model.Praga;
import br.com.geodrone.model.RegistroChuva;
import br.com.geodrone.model.RotaTrabalho;
import br.com.geodrone.model.TipoCultivo;
import br.com.geodrone.model.Usuario;

import br.com.geodrone.model.daoGen.ClienteDao;
import br.com.geodrone.model.daoGen.ConfiguracaoDao;
import br.com.geodrone.model.daoGen.DoencaDao;
import br.com.geodrone.model.daoGen.PerfilUsuarioDao;
import br.com.geodrone.model.daoGen.PontoColetaChuvaDao;
import br.com.geodrone.model.daoGen.PragaDao;
import br.com.geodrone.model.daoGen.RegistroChuvaDao;
import br.com.geodrone.model.daoGen.RotaTrabalhoDao;
import br.com.geodrone.model.daoGen.TipoCultivoDao;
import br.com.geodrone.model.daoGen.UsuarioDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig clienteDaoConfig;
    private final DaoConfig configuracaoDaoConfig;
    private final DaoConfig doencaDaoConfig;
    private final DaoConfig perfilUsuarioDaoConfig;
    private final DaoConfig pontoColetaChuvaDaoConfig;
    private final DaoConfig pragaDaoConfig;
    private final DaoConfig registroChuvaDaoConfig;
    private final DaoConfig rotaTrabalhoDaoConfig;
    private final DaoConfig tipoCultivoDaoConfig;
    private final DaoConfig usuarioDaoConfig;

    private final ClienteDao clienteDao;
    private final ConfiguracaoDao configuracaoDao;
    private final DoencaDao doencaDao;
    private final PerfilUsuarioDao perfilUsuarioDao;
    private final PontoColetaChuvaDao pontoColetaChuvaDao;
    private final PragaDao pragaDao;
    private final RegistroChuvaDao registroChuvaDao;
    private final RotaTrabalhoDao rotaTrabalhoDao;
    private final TipoCultivoDao tipoCultivoDao;
    private final UsuarioDao usuarioDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        clienteDaoConfig = daoConfigMap.get(ClienteDao.class).clone();
        clienteDaoConfig.initIdentityScope(type);

        configuracaoDaoConfig = daoConfigMap.get(ConfiguracaoDao.class).clone();
        configuracaoDaoConfig.initIdentityScope(type);

        doencaDaoConfig = daoConfigMap.get(DoencaDao.class).clone();
        doencaDaoConfig.initIdentityScope(type);

        perfilUsuarioDaoConfig = daoConfigMap.get(PerfilUsuarioDao.class).clone();
        perfilUsuarioDaoConfig.initIdentityScope(type);

        pontoColetaChuvaDaoConfig = daoConfigMap.get(PontoColetaChuvaDao.class).clone();
        pontoColetaChuvaDaoConfig.initIdentityScope(type);

        pragaDaoConfig = daoConfigMap.get(PragaDao.class).clone();
        pragaDaoConfig.initIdentityScope(type);

        registroChuvaDaoConfig = daoConfigMap.get(RegistroChuvaDao.class).clone();
        registroChuvaDaoConfig.initIdentityScope(type);

        rotaTrabalhoDaoConfig = daoConfigMap.get(RotaTrabalhoDao.class).clone();
        rotaTrabalhoDaoConfig.initIdentityScope(type);

        tipoCultivoDaoConfig = daoConfigMap.get(TipoCultivoDao.class).clone();
        tipoCultivoDaoConfig.initIdentityScope(type);

        usuarioDaoConfig = daoConfigMap.get(UsuarioDao.class).clone();
        usuarioDaoConfig.initIdentityScope(type);

        clienteDao = new ClienteDao(clienteDaoConfig, this);
        configuracaoDao = new ConfiguracaoDao(configuracaoDaoConfig, this);
        doencaDao = new DoencaDao(doencaDaoConfig, this);
        perfilUsuarioDao = new PerfilUsuarioDao(perfilUsuarioDaoConfig, this);
        pontoColetaChuvaDao = new PontoColetaChuvaDao(pontoColetaChuvaDaoConfig, this);
        pragaDao = new PragaDao(pragaDaoConfig, this);
        registroChuvaDao = new RegistroChuvaDao(registroChuvaDaoConfig, this);
        rotaTrabalhoDao = new RotaTrabalhoDao(rotaTrabalhoDaoConfig, this);
        tipoCultivoDao = new TipoCultivoDao(tipoCultivoDaoConfig, this);
        usuarioDao = new UsuarioDao(usuarioDaoConfig, this);

        registerDao(Cliente.class, clienteDao);
        registerDao(Configuracao.class, configuracaoDao);
        registerDao(Doenca.class, doencaDao);
        registerDao(PerfilUsuario.class, perfilUsuarioDao);
        registerDao(PontoColetaChuva.class, pontoColetaChuvaDao);
        registerDao(Praga.class, pragaDao);
        registerDao(RegistroChuva.class, registroChuvaDao);
        registerDao(RotaTrabalho.class, rotaTrabalhoDao);
        registerDao(TipoCultivo.class, tipoCultivoDao);
        registerDao(Usuario.class, usuarioDao);
    }
    
    public void clear() {
        clienteDaoConfig.clearIdentityScope();
        configuracaoDaoConfig.clearIdentityScope();
        doencaDaoConfig.clearIdentityScope();
        perfilUsuarioDaoConfig.clearIdentityScope();
        pontoColetaChuvaDaoConfig.clearIdentityScope();
        pragaDaoConfig.clearIdentityScope();
        registroChuvaDaoConfig.clearIdentityScope();
        rotaTrabalhoDaoConfig.clearIdentityScope();
        tipoCultivoDaoConfig.clearIdentityScope();
        usuarioDaoConfig.clearIdentityScope();
    }

    public ClienteDao getClienteDao() {
        return clienteDao;
    }

    public ConfiguracaoDao getConfiguracaoDao() {
        return configuracaoDao;
    }

    public DoencaDao getDoencaDao() {
        return doencaDao;
    }

    public PerfilUsuarioDao getPerfilUsuarioDao() {
        return perfilUsuarioDao;
    }

    public PontoColetaChuvaDao getPontoColetaChuvaDao() {
        return pontoColetaChuvaDao;
    }

    public PragaDao getPragaDao() {
        return pragaDao;
    }

    public RegistroChuvaDao getRegistroChuvaDao() {
        return registroChuvaDao;
    }

    public RotaTrabalhoDao getRotaTrabalhoDao() {
        return rotaTrabalhoDao;
    }

    public TipoCultivoDao getTipoCultivoDao() {
        return tipoCultivoDao;
    }

    public UsuarioDao getUsuarioDao() {
        return usuarioDao;
    }

}
