package br.com.geodrone.model.daoGen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import br.com.geodrone.model.DefensivoQuimico;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GEO_DEFENSIVO_QUIMICO".
*/
public class DefensivoQuimicoDao extends AbstractDao<DefensivoQuimico, Long> {

    public static final String TABLENAME = "GEO_DEFENSIVO_QUIMICO";

    /**
     * Properties of entity DefensivoQuimico.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID_DEFENSIVO_QUIMICO");
        public final static Property Descricao = new Property(1, String.class, "descricao", false, "DESCRICAO");
        public final static Property IngredientesAtivos = new Property(2, String.class, "ingredientesAtivos", false, "INGREDIENTES_ATIVOS");
        public final static Property IdTipoDefensivo = new Property(3, Long.class, "idTipoDefensivo", false, "ID_TIPO_DEFENSIVO");
        public final static Property IndAtivo = new Property(4, Integer.class, "indAtivo", false, "IND_ATIVO");
        public final static Property DtInclusao = new Property(5, java.util.Date.class, "dtInclusao", false, "DT_INCLUSAO");
        public final static Property DtAlteracao = new Property(6, java.util.Date.class, "dtAlteracao", false, "DT_ALTERACAO");
        public final static Property VersaoSistema = new Property(7, Long.class, "versaoSistema", false, "VERSAO_SISTEMA");
        public final static Property IdUsuarioReg = new Property(8, Long.class, "idUsuarioReg", false, "ID_USUARIO_REG");
    }


    public DefensivoQuimicoDao(DaoConfig config) {
        super(config);
    }
    
    public DefensivoQuimicoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GEO_DEFENSIVO_QUIMICO\" (" + //
                "\"ID_DEFENSIVO_QUIMICO\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DESCRICAO\" TEXT," + // 1: descricao
                "\"INGREDIENTES_ATIVOS\" TEXT," + // 2: ingredientesAtivos
                "\"ID_TIPO_DEFENSIVO\" INTEGER," + // 3: idTipoDefensivo
                "\"IND_ATIVO\" INTEGER NOT NULL ," + // 4: indAtivo
                "\"DT_INCLUSAO\" INTEGER NOT NULL ," + // 5: dtInclusao
                "\"DT_ALTERACAO\" INTEGER NOT NULL ," + // 6: dtAlteracao
                "\"VERSAO_SISTEMA\" INTEGER NOT NULL ," + // 7: versaoSistema
                "\"ID_USUARIO_REG\" INTEGER NOT NULL );"); // 8: idUsuarioReg
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GEO_DEFENSIVO_QUIMICO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DefensivoQuimico entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String descricao = entity.getDescricao();
        if (descricao != null) {
            stmt.bindString(2, descricao);
        }
 
        String ingredientesAtivos = entity.getIngredientesAtivos();
        if (ingredientesAtivos != null) {
            stmt.bindString(3, ingredientesAtivos);
        }
 
        Long idTipoDefensivo = entity.getIdTipoDefensivo();
        if (idTipoDefensivo != null) {
            stmt.bindLong(4, idTipoDefensivo);
        }
        stmt.bindLong(5, entity.getIndAtivo());
        stmt.bindLong(6, entity.getDtInclusao().getTime());
        stmt.bindLong(7, entity.getDtAlteracao().getTime());
        stmt.bindLong(8, entity.getVersaoSistema());
        stmt.bindLong(9, entity.getIdUsuarioReg());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DefensivoQuimico entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String descricao = entity.getDescricao();
        if (descricao != null) {
            stmt.bindString(2, descricao);
        }
 
        String ingredientesAtivos = entity.getIngredientesAtivos();
        if (ingredientesAtivos != null) {
            stmt.bindString(3, ingredientesAtivos);
        }
 
        Long idTipoDefensivo = entity.getIdTipoDefensivo();
        if (idTipoDefensivo != null) {
            stmt.bindLong(4, idTipoDefensivo);
        }
        stmt.bindLong(5, entity.getIndAtivo());
        stmt.bindLong(6, entity.getDtInclusao().getTime());
        stmt.bindLong(7, entity.getDtAlteracao().getTime());
        stmt.bindLong(8, entity.getVersaoSistema());
        stmt.bindLong(9, entity.getIdUsuarioReg());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DefensivoQuimico readEntity(Cursor cursor, int offset) {
        DefensivoQuimico entity = new DefensivoQuimico();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DefensivoQuimico entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDescricao(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIngredientesAtivos(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIdTipoDefensivo(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setIndAtivo(cursor.getInt(offset + 4));
        entity.setDtInclusao(new java.util.Date(cursor.getLong(offset + 5)));
        entity.setDtAlteracao(new java.util.Date(cursor.getLong(offset + 6)));
        entity.setVersaoSistema(cursor.getLong(offset + 7));
        entity.setIdUsuarioReg(cursor.getLong(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DefensivoQuimico entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DefensivoQuimico entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DefensivoQuimico entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
