package br.com.geodrone.model.daoGen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import br.com.geodrone.model.PerfilUsuario;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TB_PERFIL_USUARIO".
*/
public class PerfilUsuarioDao extends AbstractDao<PerfilUsuario, Long> {

    public static final String TABLENAME = "TB_PERFIL_USUARIO";

    /**
     * Properties of entity PerfilUsuario.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID_PERFIL_USUARIO");
        public final static Property Descricao = new Property(1, String.class, "descricao", false, "DESCRICAO");
        public final static Property FlagTipoPerfil = new Property(2, String.class, "flagTipoPerfil", false, "FLAG_TIPO_PERFIL");
        public final static Property DtInclusao = new Property(3, java.util.Date.class, "dtInclusao", false, "DT_INCLUSAO");
        public final static Property DtAlteracao = new Property(4, java.util.Date.class, "dtAlteracao", false, "DT_ALTERACAO");
        public final static Property VersaoSistema = new Property(5, Long.class, "versaoSistema", false, "VERSAO_SISTEMA");
    }


    public PerfilUsuarioDao(DaoConfig config) {
        super(config);
    }
    
    public PerfilUsuarioDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TB_PERFIL_USUARIO\" (" + //
                "\"ID_PERFIL_USUARIO\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DESCRICAO\" TEXT NOT NULL ," + // 1: descricao
                "\"FLAG_TIPO_PERFIL\" TEXT," + // 2: flagTipoPerfil
                "\"DT_INCLUSAO\" INTEGER NOT NULL ," + // 3: dtInclusao
                "\"DT_ALTERACAO\" INTEGER NOT NULL ," + // 4: dtAlteracao
                "\"VERSAO_SISTEMA\" INTEGER NOT NULL );"); // 5: versaoSistema
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TB_PERFIL_USUARIO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PerfilUsuario entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getDescricao());
 
        String flagTipoPerfil = entity.getFlagTipoPerfil();
        if (flagTipoPerfil != null) {
            stmt.bindString(3, flagTipoPerfil);
        }
        stmt.bindLong(4, entity.getDtInclusao().getTime());
        stmt.bindLong(5, entity.getDtAlteracao().getTime());
        stmt.bindLong(6, entity.getVersaoSistema());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PerfilUsuario entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getDescricao());
 
        String flagTipoPerfil = entity.getFlagTipoPerfil();
        if (flagTipoPerfil != null) {
            stmt.bindString(3, flagTipoPerfil);
        }
        stmt.bindLong(4, entity.getDtInclusao().getTime());
        stmt.bindLong(5, entity.getDtAlteracao().getTime());
        stmt.bindLong(6, entity.getVersaoSistema());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PerfilUsuario readEntity(Cursor cursor, int offset) {
        PerfilUsuario entity = new PerfilUsuario();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PerfilUsuario entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDescricao(cursor.getString(offset + 1));
        entity.setFlagTipoPerfil(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDtInclusao(new java.util.Date(cursor.getLong(offset + 3)));
        entity.setDtAlteracao(new java.util.Date(cursor.getLong(offset + 4)));
        entity.setVersaoSistema(cursor.getLong(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PerfilUsuario entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PerfilUsuario entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PerfilUsuario entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
