package br.com.geodrone.model.daoGen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import br.com.geodrone.model.PontoColetaChuva;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GEO_PONTO_COLETA_CHUVA".
*/
public class PontoColetaChuvaDao extends AbstractDao<PontoColetaChuva, Long> {

    public static final String TABLENAME = "GEO_PONTO_COLETA_CHUVA";

    /**
     * Properties of entity PontoColetaChuva.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID_PONTO_COLETA_CHUVA_DISP");
        public final static Property Descricao = new Property(1, String.class, "descricao", false, "DESCRICAO");
        public final static Property DtInstalacao = new Property(2, java.util.Date.class, "dtInstalacao", false, "DT_INSTALACAO");
        public final static Property IdPontoColetaChuva = new Property(3, Long.class, "idPontoColetaChuva", false, "ID_PONTO_COLETA_CHUVA");
        public final static Property IdCliente = new Property(4, Long.class, "idCliente", false, "ID_CLIENTE");
        public final static Property Latitude = new Property(5, Double.class, "latitude", false, "LATITUDE");
        public final static Property Longitude = new Property(6, Double.class, "longitude", false, "LONGITUDE");
        public final static Property IdDispositivo = new Property(7, Long.class, "idDispositivo", false, "ID_DISPOSITIVO");
        public final static Property IndAtivo = new Property(8, Integer.class, "indAtivo", false, "IND_ATIVO");
        public final static Property DtInclusao = new Property(9, java.util.Date.class, "dtInclusao", false, "DT_INCLUSAO");
        public final static Property DtAlteracao = new Property(10, java.util.Date.class, "dtAlteracao", false, "DT_ALTERACAO");
        public final static Property VersaoSistema = new Property(11, Long.class, "versaoSistema", false, "VERSAO_SISTEMA");
        public final static Property IdUsuarioReg = new Property(12, Long.class, "idUsuarioReg", false, "ID_USUARIO_REG");
    }


    public PontoColetaChuvaDao(DaoConfig config) {
        super(config);
    }
    
    public PontoColetaChuvaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GEO_PONTO_COLETA_CHUVA\" (" + //
                "\"ID_PONTO_COLETA_CHUVA_DISP\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"DESCRICAO\" TEXT," + // 1: descricao
                "\"DT_INSTALACAO\" INTEGER," + // 2: dtInstalacao
                "\"ID_PONTO_COLETA_CHUVA\" INTEGER," + // 3: idPontoColetaChuva
                "\"ID_CLIENTE\" INTEGER NOT NULL ," + // 4: idCliente
                "\"LATITUDE\" REAL NOT NULL ," + // 5: latitude
                "\"LONGITUDE\" REAL NOT NULL ," + // 6: longitude
                "\"ID_DISPOSITIVO\" INTEGER NOT NULL ," + // 7: idDispositivo
                "\"IND_ATIVO\" INTEGER NOT NULL ," + // 8: indAtivo
                "\"DT_INCLUSAO\" INTEGER NOT NULL ," + // 9: dtInclusao
                "\"DT_ALTERACAO\" INTEGER NOT NULL ," + // 10: dtAlteracao
                "\"VERSAO_SISTEMA\" INTEGER NOT NULL ," + // 11: versaoSistema
                "\"ID_USUARIO_REG\" INTEGER NOT NULL );"); // 12: idUsuarioReg
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GEO_PONTO_COLETA_CHUVA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PontoColetaChuva entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String descricao = entity.getDescricao();
        if (descricao != null) {
            stmt.bindString(2, descricao);
        }
 
        java.util.Date dtInstalacao = entity.getDtInstalacao();
        if (dtInstalacao != null) {
            stmt.bindLong(3, dtInstalacao.getTime());
        }
 
        Long idPontoColetaChuva = entity.getIdPontoColetaChuva();
        if (idPontoColetaChuva != null) {
            stmt.bindLong(4, idPontoColetaChuva);
        }
        stmt.bindLong(5, entity.getIdCliente());
        stmt.bindDouble(6, entity.getLatitude());
        stmt.bindDouble(7, entity.getLongitude());
        stmt.bindLong(8, entity.getIdDispositivo());
        stmt.bindLong(9, entity.getIndAtivo());
        stmt.bindLong(10, entity.getDtInclusao().getTime());
        stmt.bindLong(11, entity.getDtAlteracao().getTime());
        stmt.bindLong(12, entity.getVersaoSistema());
        stmt.bindLong(13, entity.getIdUsuarioReg());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PontoColetaChuva entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String descricao = entity.getDescricao();
        if (descricao != null) {
            stmt.bindString(2, descricao);
        }
 
        java.util.Date dtInstalacao = entity.getDtInstalacao();
        if (dtInstalacao != null) {
            stmt.bindLong(3, dtInstalacao.getTime());
        }
 
        Long idPontoColetaChuva = entity.getIdPontoColetaChuva();
        if (idPontoColetaChuva != null) {
            stmt.bindLong(4, idPontoColetaChuva);
        }
        stmt.bindLong(5, entity.getIdCliente());
        stmt.bindDouble(6, entity.getLatitude());
        stmt.bindDouble(7, entity.getLongitude());
        stmt.bindLong(8, entity.getIdDispositivo());
        stmt.bindLong(9, entity.getIndAtivo());
        stmt.bindLong(10, entity.getDtInclusao().getTime());
        stmt.bindLong(11, entity.getDtAlteracao().getTime());
        stmt.bindLong(12, entity.getVersaoSistema());
        stmt.bindLong(13, entity.getIdUsuarioReg());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PontoColetaChuva readEntity(Cursor cursor, int offset) {
        PontoColetaChuva entity = new PontoColetaChuva();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PontoColetaChuva entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDescricao(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDtInstalacao(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setIdPontoColetaChuva(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setIdCliente(cursor.getLong(offset + 4));
        entity.setLatitude(cursor.getDouble(offset + 5));
        entity.setLongitude(cursor.getDouble(offset + 6));
        entity.setIdDispositivo(cursor.getLong(offset + 7));
        entity.setIndAtivo(cursor.getInt(offset + 8));
        entity.setDtInclusao(new java.util.Date(cursor.getLong(offset + 9)));
        entity.setDtAlteracao(new java.util.Date(cursor.getLong(offset + 10)));
        entity.setVersaoSistema(cursor.getLong(offset + 11));
        entity.setIdUsuarioReg(cursor.getLong(offset + 12));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PontoColetaChuva entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PontoColetaChuva entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PontoColetaChuva entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
