package br.com.geodrone.model.daoGen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import br.com.geodrone.model.Praga;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TB_PRAGA".
*/
public class PragaDao extends AbstractDao<Praga, Long> {

    public static final String TABLENAME = "TB_PRAGA";

    /**
     * Properties of entity Praga.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property IdPragaRef = new Property(0, Long.class, "idPragaRef", true, "ID_PRAGA_REF");
        public final static Property IdTipoCultivoRef = new Property(1, Long.class, "idTipoCultivoRef", false, "ID_TIPO_CULTIVO_REF");
        public final static Property Descricao = new Property(2, String.class, "descricao", false, "DESCRICAO");
        public final static Property DescricaoCientifica = new Property(3, String.class, "descricaoCientifica", false, "DESCRICAO_CIENTIFICA");
        public final static Property IndAtivo = new Property(4, Integer.class, "indAtivo", false, "IND_ATIVO");
    }


    public PragaDao(DaoConfig config) {
        super(config);
    }
    
    public PragaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TB_PRAGA\" (" + //
                "\"ID_PRAGA_REF\" INTEGER PRIMARY KEY ," + // 0: idPragaRef
                "\"ID_TIPO_CULTIVO_REF\" INTEGER," + // 1: idTipoCultivoRef
                "\"DESCRICAO\" TEXT NOT NULL ," + // 2: descricao
                "\"DESCRICAO_CIENTIFICA\" TEXT NOT NULL ," + // 3: descricaoCientifica
                "\"IND_ATIVO\" INTEGER NOT NULL );"); // 4: indAtivo
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TB_PRAGA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Praga entity) {
        stmt.clearBindings();
 
        Long idPragaRef = entity.getIdPragaRef();
        if (idPragaRef != null) {
            stmt.bindLong(1, idPragaRef);
        }
 
        Long idTipoCultivoRef = entity.getIdTipoCultivoRef();
        if (idTipoCultivoRef != null) {
            stmt.bindLong(2, idTipoCultivoRef);
        }
        stmt.bindString(3, entity.getDescricao());
        stmt.bindString(4, entity.getDescricaoCientifica());
        stmt.bindLong(5, entity.getIndAtivo());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Praga entity) {
        stmt.clearBindings();
 
        Long idPragaRef = entity.getIdPragaRef();
        if (idPragaRef != null) {
            stmt.bindLong(1, idPragaRef);
        }
 
        Long idTipoCultivoRef = entity.getIdTipoCultivoRef();
        if (idTipoCultivoRef != null) {
            stmt.bindLong(2, idTipoCultivoRef);
        }
        stmt.bindString(3, entity.getDescricao());
        stmt.bindString(4, entity.getDescricaoCientifica());
        stmt.bindLong(5, entity.getIndAtivo());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Praga readEntity(Cursor cursor, int offset) {
        Praga entity = new Praga();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Praga entity, int offset) {
        entity.setIdPragaRef(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdTipoCultivoRef(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setDescricao(cursor.getString(offset + 2));
        entity.setDescricaoCientifica(cursor.getString(offset + 3));
        entity.setIndAtivo(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Praga entity, long rowId) {
        entity.setIdPragaRef(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Praga entity) {
        if(entity != null) {
            return entity.getIdPragaRef();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Praga entity) {
        return entity.getIdPragaRef() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
