package br.com.geodrone.model.daoGen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import br.com.geodrone.model.RegistroChuva;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TB_REGISTRO_CHUVA".
*/
public class RegistroChuvaDao extends AbstractDao<RegistroChuva, Long> {

    public static final String TABLENAME = "TB_REGISTRO_CHUVA";

    /**
     * Properties of entity RegistroChuva.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property IdRegistroChuva = new Property(0, Long.class, "idRegistroChuva", true, "ID_REGISTRO_CHUVA");
        public final static Property IdClienteRef = new Property(1, Long.class, "idClienteRef", false, "ID_CLIENTE_REF");
        public final static Property Volume = new Property(2, Long.class, "volume", false, "VOLUME");
        public final static Property DtInclusao = new Property(3, java.util.Date.class, "dtInclusao", false, "DT_INCLUSAO");
        public final static Property DtAlteracao = new Property(4, java.util.Date.class, "dtAlteracao", false, "DT_ALTERACAO");
        public final static Property IdUsuario = new Property(5, Long.class, "idUsuario", false, "ID_USUARIO");
        public final static Property IdRegistroChuvaRef = new Property(6, Long.class, "idRegistroChuvaRef", false, "ID_REGISTRO_CHUVA_REF");
    }


    public RegistroChuvaDao(DaoConfig config) {
        super(config);
    }
    
    public RegistroChuvaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TB_REGISTRO_CHUVA\" (" + //
                "\"ID_REGISTRO_CHUVA\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: idRegistroChuva
                "\"ID_CLIENTE_REF\" INTEGER NOT NULL ," + // 1: idClienteRef
                "\"VOLUME\" INTEGER NOT NULL ," + // 2: volume
                "\"DT_INCLUSAO\" INTEGER NOT NULL ," + // 3: dtInclusao
                "\"DT_ALTERACAO\" INTEGER NOT NULL ," + // 4: dtAlteracao
                "\"ID_USUARIO\" INTEGER," + // 5: idUsuario
                "\"ID_REGISTRO_CHUVA_REF\" INTEGER);"); // 6: idRegistroChuvaRef
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TB_REGISTRO_CHUVA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RegistroChuva entity) {
        stmt.clearBindings();
 
        Long idRegistroChuva = entity.getIdRegistroChuva();
        if (idRegistroChuva != null) {
            stmt.bindLong(1, idRegistroChuva);
        }
        stmt.bindLong(2, entity.getIdClienteRef());
        stmt.bindLong(3, entity.getVolume());
        stmt.bindLong(4, entity.getDtInclusao().getTime());
        stmt.bindLong(5, entity.getDtAlteracao().getTime());
 
        Long idUsuario = entity.getIdUsuario();
        if (idUsuario != null) {
            stmt.bindLong(6, idUsuario);
        }
 
        Long idRegistroChuvaRef = entity.getIdRegistroChuvaRef();
        if (idRegistroChuvaRef != null) {
            stmt.bindLong(7, idRegistroChuvaRef);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RegistroChuva entity) {
        stmt.clearBindings();
 
        Long idRegistroChuva = entity.getIdRegistroChuva();
        if (idRegistroChuva != null) {
            stmt.bindLong(1, idRegistroChuva);
        }
        stmt.bindLong(2, entity.getIdClienteRef());
        stmt.bindLong(3, entity.getVolume());
        stmt.bindLong(4, entity.getDtInclusao().getTime());
        stmt.bindLong(5, entity.getDtAlteracao().getTime());
 
        Long idUsuario = entity.getIdUsuario();
        if (idUsuario != null) {
            stmt.bindLong(6, idUsuario);
        }
 
        Long idRegistroChuvaRef = entity.getIdRegistroChuvaRef();
        if (idRegistroChuvaRef != null) {
            stmt.bindLong(7, idRegistroChuvaRef);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RegistroChuva readEntity(Cursor cursor, int offset) {
        RegistroChuva entity = new RegistroChuva();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RegistroChuva entity, int offset) {
        entity.setIdRegistroChuva(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdClienteRef(cursor.getLong(offset + 1));
        entity.setVolume(cursor.getLong(offset + 2));
        entity.setDtInclusao(new java.util.Date(cursor.getLong(offset + 3)));
        entity.setDtAlteracao(new java.util.Date(cursor.getLong(offset + 4)));
        entity.setIdUsuario(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setIdRegistroChuvaRef(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RegistroChuva entity, long rowId) {
        entity.setIdRegistroChuva(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RegistroChuva entity) {
        if(entity != null) {
            return entity.getIdRegistroChuva();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RegistroChuva entity) {
        return entity.getIdRegistroChuva() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
