package br.com.geodrone.model.daoGen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import br.com.geodrone.model.RegistroPraga;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TB_REGISTRO_PRAGA".
*/
public class RegistroPragaDao extends AbstractDao<RegistroPraga, Long> {

    public static final String TABLENAME = "TB_REGISTRO_PRAGA";

    /**
     * Properties of entity RegistroPraga.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property IdRegistroChuva = new Property(0, Long.class, "idRegistroChuva", true, "ID_REGISTRO_PRAGA");
        public final static Property IdPragaRef = new Property(1, Long.class, "idPragaRef", false, "ID_PRAGA_REF");
        public final static Property IdClienteRef = new Property(2, Long.class, "idClienteRef", false, "ID_CLIENTE_REF");
        public final static Property Latitude = new Property(3, Double.class, "latitude", false, "LATITUDE");
        public final static Property Longitude = new Property(4, Double.class, "longitude", false, "LONGITUDE");
        public final static Property Observacao = new Property(5, String.class, "observacao", false, "OBSERVACAO");
        public final static Property Qtde = new Property(6, Integer.class, "qtde", false, "QTDE");
        public final static Property DtInclusao = new Property(7, java.util.Date.class, "dtInclusao", false, "DT_INCLUSAO");
        public final static Property DtAlteracao = new Property(8, java.util.Date.class, "dtAlteracao", false, "DT_ALTERACAO");
        public final static Property IdUsuario = new Property(9, Long.class, "idUsuario", false, "ID_USUARIO");
        public final static Property IdRegistroChuvaRef = new Property(10, Long.class, "idRegistroChuvaRef", false, "ID_REGISTRO_PRAGA_REF");
        public final static Property IdDispositivo = new Property(11, Long.class, "idDispositivo", false, "ID_DISPOSITIVO");
    }


    public RegistroPragaDao(DaoConfig config) {
        super(config);
    }
    
    public RegistroPragaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TB_REGISTRO_PRAGA\" (" + //
                "\"ID_REGISTRO_PRAGA\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: idRegistroChuva
                "\"ID_PRAGA_REF\" INTEGER NOT NULL ," + // 1: idPragaRef
                "\"ID_CLIENTE_REF\" INTEGER NOT NULL ," + // 2: idClienteRef
                "\"LATITUDE\" REAL NOT NULL ," + // 3: latitude
                "\"LONGITUDE\" REAL NOT NULL ," + // 4: longitude
                "\"OBSERVACAO\" TEXT," + // 5: observacao
                "\"QTDE\" INTEGER NOT NULL ," + // 6: qtde
                "\"DT_INCLUSAO\" INTEGER NOT NULL ," + // 7: dtInclusao
                "\"DT_ALTERACAO\" INTEGER NOT NULL ," + // 8: dtAlteracao
                "\"ID_USUARIO\" INTEGER NOT NULL ," + // 9: idUsuario
                "\"ID_REGISTRO_PRAGA_REF\" INTEGER," + // 10: idRegistroChuvaRef
                "\"ID_DISPOSITIVO\" INTEGER);"); // 11: idDispositivo
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TB_REGISTRO_PRAGA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RegistroPraga entity) {
        stmt.clearBindings();
 
        Long idRegistroChuva = entity.getIdRegistroChuva();
        if (idRegistroChuva != null) {
            stmt.bindLong(1, idRegistroChuva);
        }
        stmt.bindLong(2, entity.getIdPragaRef());
        stmt.bindLong(3, entity.getIdClienteRef());
        stmt.bindDouble(4, entity.getLatitude());
        stmt.bindDouble(5, entity.getLongitude());
 
        String observacao = entity.getObservacao();
        if (observacao != null) {
            stmt.bindString(6, observacao);
        }
        stmt.bindLong(7, entity.getQtde());
        stmt.bindLong(8, entity.getDtInclusao().getTime());
        stmt.bindLong(9, entity.getDtAlteracao().getTime());
        stmt.bindLong(10, entity.getIdUsuario());
 
        Long idRegistroChuvaRef = entity.getIdRegistroChuvaRef();
        if (idRegistroChuvaRef != null) {
            stmt.bindLong(11, idRegistroChuvaRef);
        }
 
        Long idDispositivo = entity.getIdDispositivo();
        if (idDispositivo != null) {
            stmt.bindLong(12, idDispositivo);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RegistroPraga entity) {
        stmt.clearBindings();
 
        Long idRegistroChuva = entity.getIdRegistroChuva();
        if (idRegistroChuva != null) {
            stmt.bindLong(1, idRegistroChuva);
        }
        stmt.bindLong(2, entity.getIdPragaRef());
        stmt.bindLong(3, entity.getIdClienteRef());
        stmt.bindDouble(4, entity.getLatitude());
        stmt.bindDouble(5, entity.getLongitude());
 
        String observacao = entity.getObservacao();
        if (observacao != null) {
            stmt.bindString(6, observacao);
        }
        stmt.bindLong(7, entity.getQtde());
        stmt.bindLong(8, entity.getDtInclusao().getTime());
        stmt.bindLong(9, entity.getDtAlteracao().getTime());
        stmt.bindLong(10, entity.getIdUsuario());
 
        Long idRegistroChuvaRef = entity.getIdRegistroChuvaRef();
        if (idRegistroChuvaRef != null) {
            stmt.bindLong(11, idRegistroChuvaRef);
        }
 
        Long idDispositivo = entity.getIdDispositivo();
        if (idDispositivo != null) {
            stmt.bindLong(12, idDispositivo);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RegistroPraga readEntity(Cursor cursor, int offset) {
        RegistroPraga entity = new RegistroPraga();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RegistroPraga entity, int offset) {
        entity.setIdRegistroChuva(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdPragaRef(cursor.getLong(offset + 1));
        entity.setIdClienteRef(cursor.getLong(offset + 2));
        entity.setLatitude(cursor.getDouble(offset + 3));
        entity.setLongitude(cursor.getDouble(offset + 4));
        entity.setObservacao(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setQtde(cursor.getInt(offset + 6));
        entity.setDtInclusao(new java.util.Date(cursor.getLong(offset + 7)));
        entity.setDtAlteracao(new java.util.Date(cursor.getLong(offset + 8)));
        entity.setIdUsuario(cursor.getLong(offset + 9));
        entity.setIdRegistroChuvaRef(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
        entity.setIdDispositivo(cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RegistroPraga entity, long rowId) {
        entity.setIdRegistroChuva(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RegistroPraga entity) {
        if(entity != null) {
            return entity.getIdRegistroChuva();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RegistroPraga entity) {
        return entity.getIdRegistroChuva() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
