package br.com.geodrone.model.daoGen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import br.com.geodrone.model.RegistroChuva;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GEO_REGISTRO_CHUVA".
*/
public class RegistroChuvaDao extends AbstractDao<RegistroChuva, Long> {

    public static final String TABLENAME = "GEO_REGISTRO_CHUVA";

    /**
     * Properties of entity RegistroChuva.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID_REGISTRO_CHUVA_DISP");
        public final static Property Volume = new Property(1, Integer.class, "volume", false, "VOLUME");
        public final static Property Observacao = new Property(2, String.class, "observacao", false, "OBSERVACAO");
        public final static Property IdPontoColetaChuvaDisp = new Property(3, Long.class, "idPontoColetaChuvaDisp", false, "ID_PONTO_COLETA_CHUVA_DISP");
        public final static Property IdRegistroChuva = new Property(4, Long.class, "idRegistroChuva", false, "ID_REGISTRO_CHUVA");
        public final static Property DtRegistro = new Property(5, java.util.Date.class, "dtRegistro", false, "DT_REGISTRO");
        public final static Property IdCliente = new Property(6, Long.class, "idCliente", false, "ID_CLIENTE");
        public final static Property Latitude = new Property(7, Double.class, "latitude", false, "LATITUDE");
        public final static Property Longitude = new Property(8, Double.class, "longitude", false, "LONGITUDE");
        public final static Property IdDispositivo = new Property(9, Long.class, "idDispositivo", false, "ID_DISPOSITIVO");
        public final static Property DtInclusao = new Property(10, java.util.Date.class, "dtInclusao", false, "DT_INCLUSAO");
        public final static Property DtAlteracao = new Property(11, java.util.Date.class, "dtAlteracao", false, "DT_ALTERACAO");
        public final static Property VersaoSistema = new Property(12, Long.class, "versaoSistema", false, "VERSAO_SISTEMA");
        public final static Property IdUsuarioReg = new Property(13, Long.class, "idUsuarioReg", false, "ID_USUARIO_REG");
    }


    public RegistroChuvaDao(DaoConfig config) {
        super(config);
    }
    
    public RegistroChuvaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GEO_REGISTRO_CHUVA\" (" + //
                "\"ID_REGISTRO_CHUVA_DISP\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"VOLUME\" INTEGER," + // 1: volume
                "\"OBSERVACAO\" TEXT," + // 2: observacao
                "\"ID_PONTO_COLETA_CHUVA_DISP\" INTEGER," + // 3: idPontoColetaChuvaDisp
                "\"ID_REGISTRO_CHUVA\" INTEGER," + // 4: idRegistroChuva
                "\"DT_REGISTRO\" INTEGER NOT NULL ," + // 5: dtRegistro
                "\"ID_CLIENTE\" INTEGER NOT NULL ," + // 6: idCliente
                "\"LATITUDE\" REAL NOT NULL ," + // 7: latitude
                "\"LONGITUDE\" REAL NOT NULL ," + // 8: longitude
                "\"ID_DISPOSITIVO\" INTEGER NOT NULL ," + // 9: idDispositivo
                "\"DT_INCLUSAO\" INTEGER NOT NULL ," + // 10: dtInclusao
                "\"DT_ALTERACAO\" INTEGER NOT NULL ," + // 11: dtAlteracao
                "\"VERSAO_SISTEMA\" INTEGER NOT NULL ," + // 12: versaoSistema
                "\"ID_USUARIO_REG\" INTEGER NOT NULL );"); // 13: idUsuarioReg
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GEO_REGISTRO_CHUVA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RegistroChuva entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer volume = entity.getVolume();
        if (volume != null) {
            stmt.bindLong(2, volume);
        }
 
        String observacao = entity.getObservacao();
        if (observacao != null) {
            stmt.bindString(3, observacao);
        }
 
        Long idPontoColetaChuvaDisp = entity.getIdPontoColetaChuvaDisp();
        if (idPontoColetaChuvaDisp != null) {
            stmt.bindLong(4, idPontoColetaChuvaDisp);
        }
 
        Long idRegistroChuva = entity.getIdRegistroChuva();
        if (idRegistroChuva != null) {
            stmt.bindLong(5, idRegistroChuva);
        }
        stmt.bindLong(6, entity.getDtRegistro().getTime());
        stmt.bindLong(7, entity.getIdCliente());
        stmt.bindDouble(8, entity.getLatitude());
        stmt.bindDouble(9, entity.getLongitude());
        stmt.bindLong(10, entity.getIdDispositivo());
        stmt.bindLong(11, entity.getDtInclusao().getTime());
        stmt.bindLong(12, entity.getDtAlteracao().getTime());
        stmt.bindLong(13, entity.getVersaoSistema());
        stmt.bindLong(14, entity.getIdUsuarioReg());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RegistroChuva entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer volume = entity.getVolume();
        if (volume != null) {
            stmt.bindLong(2, volume);
        }
 
        String observacao = entity.getObservacao();
        if (observacao != null) {
            stmt.bindString(3, observacao);
        }
 
        Long idPontoColetaChuvaDisp = entity.getIdPontoColetaChuvaDisp();
        if (idPontoColetaChuvaDisp != null) {
            stmt.bindLong(4, idPontoColetaChuvaDisp);
        }
 
        Long idRegistroChuva = entity.getIdRegistroChuva();
        if (idRegistroChuva != null) {
            stmt.bindLong(5, idRegistroChuva);
        }
        stmt.bindLong(6, entity.getDtRegistro().getTime());
        stmt.bindLong(7, entity.getIdCliente());
        stmt.bindDouble(8, entity.getLatitude());
        stmt.bindDouble(9, entity.getLongitude());
        stmt.bindLong(10, entity.getIdDispositivo());
        stmt.bindLong(11, entity.getDtInclusao().getTime());
        stmt.bindLong(12, entity.getDtAlteracao().getTime());
        stmt.bindLong(13, entity.getVersaoSistema());
        stmt.bindLong(14, entity.getIdUsuarioReg());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RegistroChuva readEntity(Cursor cursor, int offset) {
        RegistroChuva entity = new RegistroChuva();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RegistroChuva entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVolume(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setObservacao(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIdPontoColetaChuvaDisp(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setIdRegistroChuva(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setDtRegistro(new java.util.Date(cursor.getLong(offset + 5)));
        entity.setIdCliente(cursor.getLong(offset + 6));
        entity.setLatitude(cursor.getDouble(offset + 7));
        entity.setLongitude(cursor.getDouble(offset + 8));
        entity.setIdDispositivo(cursor.getLong(offset + 9));
        entity.setDtInclusao(new java.util.Date(cursor.getLong(offset + 10)));
        entity.setDtAlteracao(new java.util.Date(cursor.getLong(offset + 11)));
        entity.setVersaoSistema(cursor.getLong(offset + 12));
        entity.setIdUsuarioReg(cursor.getLong(offset + 13));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RegistroChuva entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RegistroChuva entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RegistroChuva entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
