package br.com.geodrone.model.daoGen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import br.com.geodrone.model.TipoDefensivo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GEO_TIPO_DEFENSIVO".
*/
public class TipoDefensivoDao extends AbstractDao<TipoDefensivo, Long> {

    public static final String TABLENAME = "GEO_TIPO_DEFENSIVO";

    /**
     * Properties of entity TipoDefensivo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID_TIPO_DEFENSIVO");
        public final static Property Descricao = new Property(1, String.class, "descricao", false, "DESCRICAO");
        public final static Property IndAtivo = new Property(2, Integer.class, "indAtivo", false, "IND_ATIVO");
        public final static Property DtInclusao = new Property(3, java.util.Date.class, "dtInclusao", false, "DT_INCLUSAO");
        public final static Property DtAlteracao = new Property(4, java.util.Date.class, "dtAlteracao", false, "DT_ALTERACAO");
        public final static Property VersaoSistema = new Property(5, Long.class, "versaoSistema", false, "VERSAO_SISTEMA");
        public final static Property IdUsuarioReg = new Property(6, Long.class, "idUsuarioReg", false, "ID_USUARIO_REG");
    }


    public TipoDefensivoDao(DaoConfig config) {
        super(config);
    }
    
    public TipoDefensivoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GEO_TIPO_DEFENSIVO\" (" + //
                "\"ID_TIPO_DEFENSIVO\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DESCRICAO\" TEXT NOT NULL ," + // 1: descricao
                "\"IND_ATIVO\" INTEGER NOT NULL ," + // 2: indAtivo
                "\"DT_INCLUSAO\" INTEGER NOT NULL ," + // 3: dtInclusao
                "\"DT_ALTERACAO\" INTEGER NOT NULL ," + // 4: dtAlteracao
                "\"VERSAO_SISTEMA\" INTEGER NOT NULL ," + // 5: versaoSistema
                "\"ID_USUARIO_REG\" INTEGER NOT NULL );"); // 6: idUsuarioReg
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GEO_TIPO_DEFENSIVO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TipoDefensivo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getDescricao());
        stmt.bindLong(3, entity.getIndAtivo());
        stmt.bindLong(4, entity.getDtInclusao().getTime());
        stmt.bindLong(5, entity.getDtAlteracao().getTime());
        stmt.bindLong(6, entity.getVersaoSistema());
        stmt.bindLong(7, entity.getIdUsuarioReg());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TipoDefensivo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getDescricao());
        stmt.bindLong(3, entity.getIndAtivo());
        stmt.bindLong(4, entity.getDtInclusao().getTime());
        stmt.bindLong(5, entity.getDtAlteracao().getTime());
        stmt.bindLong(6, entity.getVersaoSistema());
        stmt.bindLong(7, entity.getIdUsuarioReg());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TipoDefensivo readEntity(Cursor cursor, int offset) {
        TipoDefensivo entity = new TipoDefensivo();
        readEntity(cursor, entity, offset);
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TipoDefensivo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDescricao(cursor.getString(offset + 1));
        entity.setIndAtivo(cursor.getInt(offset + 2));
        entity.setDtInclusao(new java.util.Date(cursor.getLong(offset + 3)));
        entity.setDtAlteracao(new java.util.Date(cursor.getLong(offset + 4)));
        entity.setVersaoSistema(cursor.getLong(offset + 5));
        entity.setIdUsuarioReg(cursor.getLong(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TipoDefensivo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TipoDefensivo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TipoDefensivo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
